version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    ports:
      - "9090:9090"
      - "9091:9091"
    networks:
      - prometheus-net
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - prometheus-net
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - prometheus_data:/prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  prometheus-net:

