global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sql_exporter'  # Corregí el nombre del job y ajusté la indentación
    static_configs:
      - targets: ['191.101.14.79:9104']




# # my global config
# global:
#   scrape_interval:     15s # Set the interval to every 15 seconds
#   evaluation_interval: 1m # Evaluate rules every 1 minute

#   # Scrape targets from standard input, console or from a file
#   scrape_configs:
#     - job_name: 'my_app'
#       static_configs:
#         - targets: ['localhost:80']

#     - job_name: mysql # To get metrics about the mysql exporter’s targets
#       params:
#         # Not required. Will match value to child in config file. Default value is `client`.
#         auth_module: [client.servers]
#       static_configs:
#         - targets:
#           # All mysql hostnames or unix sockets to monitor.
#           - server1:3306
#       relabel_configs:
#         - source_labels: [__address__]
#           target_label: __param_target
#         - source_labels: [__param_target]
#           target_label: instance
#         - target_label: __address__
#           # The mysqld_exporter host:port
#           replacement: 191.101.14.79:9104